"""initial schema

Revision ID: 6dc07edd53e5
Revises: 
Create Date: 2026-03-09 10:10:33.564570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dc07edd53e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuisines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('itineraries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('area_name', sa.String(length=100), nullable=True),
    sa.Column('budget_total', sa.Float(), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_estimated_spend', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_genres',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('neighborhoods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('transit_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('line_names', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('venue_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('vibe_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('venues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('venue_type_id', sa.Uuid(), nullable=False),
    sa.Column('neighborhood_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('price_band', sa.Integer(), nullable=False),
    sa.Column('average_spend_gbp', sa.Float(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('booking_url', sa.String(length=500), nullable=True),
    sa.Column('is_bookable', sa.Boolean(), nullable=False),
    sa.Column('good_for_date', sa.Boolean(), nullable=False),
    sa.Column('good_for_group', sa.Boolean(), nullable=False),
    sa.Column('good_for_late_night', sa.Boolean(), nullable=False),
    sa.Column('closes_after_midnight', sa.Boolean(), nullable=False),
    sa.Column('noise_level', sa.Integer(), nullable=False),
    sa.Column('dress_code', sa.String(length=100), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ),
    sa.ForeignKeyConstraint(['venue_type_id'], ['venue_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_slug'), 'venues', ['slug'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('venue_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('genre', sa.String(length=60), nullable=True),
    sa.Column('estimated_cover_gbp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itinerary_stops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('itinerary_id', sa.Uuid(), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Uuid(), nullable=False),
    sa.Column('estimated_arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_spend_gbp', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opening_hours',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('venue_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.String(length=5), nullable=False),
    sa.Column('closes_at', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue_cuisines',
    sa.Column('venue_id', sa.Uuid(), nullable=False),
    sa.Column('cuisine_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cuisine_id'], ['cuisines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('venue_id', 'cuisine_id')
    )
    op.create_table('venue_music_genres',
    sa.Column('venue_id', sa.Uuid(), nullable=False),
    sa.Column('music_genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['music_genre_id'], ['music_genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('venue_id', 'music_genre_id')
    )
    op.create_table('venue_similarity',
    sa.Column('venue_id', sa.Uuid(), nullable=False),
    sa.Column('similar_venue_id', sa.Uuid(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['similar_venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('venue_id', 'similar_venue_id')
    )
    op.create_table('venue_transit_nodes',
    sa.Column('venue_id', sa.Uuid(), nullable=False),
    sa.Column('transit_node_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['transit_node_id'], ['transit_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('venue_id', 'transit_node_id')
    )
    op.create_table('venue_vibe_tags',
    sa.Column('venue_id', sa.Uuid(), nullable=False),
    sa.Column('vibe_tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vibe_tag_id'], ['vibe_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('venue_id', 'vibe_tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_vibe_tags')
    op.drop_table('venue_transit_nodes')
    op.drop_table('venue_similarity')
    op.drop_table('venue_music_genres')
    op.drop_table('venue_cuisines')
    op.drop_table('opening_hours')
    op.drop_table('itinerary_stops')
    op.drop_table('events')
    op.drop_index(op.f('ix_venues_slug'), table_name='venues')
    op.drop_table('venues')
    op.drop_table('vibe_tags')
    op.drop_table('venue_types')
    op.drop_table('transit_nodes')
    op.drop_table('neighborhoods')
    op.drop_table('music_genres')
    op.drop_table('itineraries')
    op.drop_table('cuisines')
    # ### end Alembic commands ###
