"""Seed fixture data for DarkKnight v1."""

NEIGHBORHOODS = [
    {"name": "Soho", "slug": "soho", "lat": 51.5133, "lng": -0.1363, "description": "The beating heart of London nightlife — bars, restaurants, and late-night culture packed into tight streets."},
    {"name": "Shoreditch", "slug": "shoreditch", "lat": 51.5255, "lng": -0.0795, "description": "East London's creative hub with street art, indie venues, rooftop bars, and warehouse clubs."},
    {"name": "Camden", "slug": "camden", "lat": 51.5392, "lng": -0.1426, "description": "Live music capital of London — grungy pubs, canal-side bars, and legendary music venues."},
    {"name": "Peckham", "slug": "peckham", "lat": 51.4735, "lng": -0.0697, "description": "South London's coolest neighbourhood with rooftop bars, natural wine spots, and community energy."},
    {"name": "Hackney", "slug": "hackney", "lat": 51.5465, "lng": -0.0555, "description": "Diverse and dynamic — craft cocktails, neighbourhood restaurants, and some of London's best small clubs."},
    {"name": "Covent Garden", "slug": "covent-garden", "lat": 51.5117, "lng": -0.1226, "description": "Theatreland dining and drinking — polished restaurants, cocktail bars, and tourist-friendly classics."},
    {"name": "Notting Hill", "slug": "notting-hill", "lat": 51.5097, "lng": -0.1970, "description": "Charming neighbourhood with wine bars, fine dining, and Portobello Road's colourful market culture."},
    {"name": "Dalston", "slug": "dalston", "lat": 51.5484, "lng": -0.0754, "description": "Late-night Dalston — dive bars, all-night clubs, and a fiercely independent food and drink scene."},
    {"name": "London Bridge", "slug": "london-bridge", "lat": 51.5055, "lng": -0.0875, "description": "Borough Market, riverside dining, and a growing cluster of cocktail bars and underground clubs."},
    {"name": "Brixton", "slug": "brixton", "lat": 51.4613, "lng": -0.1156, "description": "South London's music and nightlife powerhouse — clubs, street food, and community-driven bars."},
]

VENUE_TYPES = [
    {"name": "restaurant", "slug": "restaurant"},
    {"name": "bar", "slug": "bar"},
    {"name": "club", "slug": "club"},
]

VIBE_TAGS = [
    "stylish", "romantic", "lively", "chaotic", "relaxed", "intimate",
    "bougie", "affordable", "music-forward", "wine-led", "date-night",
    "group-friendly", "late-night",
]

CUISINES = [
    "Italian", "Japanese", "French", "Modern European", "Middle Eastern",
    "British", "Korean", "Thai", "Mexican", "Steakhouse",
]

MUSIC_GENRES = [
    "house", "techno", "disco", "hip hop", "afrobeats", "jazz",
    "open format", "live music",
]

TRANSIT_NODES = [
    {"name": "Tottenham Court Road", "lat": 51.5165, "lng": -0.1310, "lines": ["Northern", "Central", "Elizabeth"]},
    {"name": "Leicester Square", "lat": 51.5113, "lng": -0.1281, "lines": ["Northern", "Piccadilly"]},
    {"name": "Piccadilly Circus", "lat": 51.5100, "lng": -0.1337, "lines": ["Bakerloo", "Piccadilly"]},
    {"name": "Liverpool Street", "lat": 51.5178, "lng": -0.0823, "lines": ["Central", "Circle", "Hammersmith", "Metropolitan", "Elizabeth"]},
    {"name": "Old Street", "lat": 51.5258, "lng": -0.0877, "lines": ["Northern"]},
    {"name": "Shoreditch High Street", "lat": 51.5234, "lng": -0.0756, "lines": ["Overground"]},
    {"name": "Camden Town", "lat": 51.5392, "lng": -0.1426, "lines": ["Northern"]},
    {"name": "Chalk Farm", "lat": 51.5441, "lng": -0.1538, "lines": ["Northern"]},
    {"name": "Peckham Rye", "lat": 51.4697, "lng": -0.0694, "lines": ["Overground"]},
    {"name": "Hackney Central", "lat": 51.5468, "lng": -0.0566, "lines": ["Overground"]},
    {"name": "Hackney Downs", "lat": 51.5489, "lng": -0.0605, "lines": ["Overground"]},
    {"name": "Covent Garden", "lat": 51.5129, "lng": -0.1243, "lines": ["Piccadilly"]},
    {"name": "Holborn", "lat": 51.5174, "lng": -0.1200, "lines": ["Central", "Piccadilly"]},
    {"name": "Notting Hill Gate", "lat": 51.5090, "lng": -0.1963, "lines": ["Central", "Circle", "District"]},
    {"name": "Ladbroke Grove", "lat": 51.5172, "lng": -0.2107, "lines": ["Hammersmith", "Circle"]},
    {"name": "Dalston Junction", "lat": 51.5462, "lng": -0.0753, "lines": ["Overground"]},
    {"name": "Dalston Kingsland", "lat": 51.5484, "lng": -0.0762, "lines": ["Overground"]},
    {"name": "London Bridge", "lat": 51.5055, "lng": -0.0861, "lines": ["Northern", "Jubilee"]},
    {"name": "Borough", "lat": 51.5011, "lng": -0.0934, "lines": ["Northern"]},
    {"name": "Brixton", "lat": 51.4613, "lng": -0.1148, "lines": ["Victoria"]},
]

# Streets per neighborhood for address generation
STREETS = {
    "soho": ["Wardour St", "Dean St", "Old Compton St", "Greek St", "Frith St", "Berwick St"],
    "shoreditch": ["Curtain Rd", "Great Eastern St", "Rivington St", "Redchurch St", "Bethnal Green Rd", "Shoreditch High St"],
    "camden": ["Camden High St", "Chalk Farm Rd", "Kentish Town Rd", "Parkway", "Inverness St", "Delancey St"],
    "peckham": ["Rye Lane", "Peckham High St", "Bellenden Rd", "Blenheim Grove", "Holly Grove"],
    "hackney": ["Mare St", "Morning Lane", "Amhurst Rd", "Kingsland Rd", "Graham Rd"],
    "covent-garden": ["Long Acre", "Drury Lane", "Bow St", "Monmouth St", "Neal St"],
    "notting-hill": ["Portobello Rd", "Westbourne Grove", "Ledbury Rd", "Kensington Park Rd", "Pembridge Rd"],
    "dalston": ["Kingsland High St", "Ridley Rd", "Dalston Lane", "Shacklewell Lane", "Arcola St"],
    "london-bridge": ["Borough High St", "Bermondsey St", "Tooley St", "Stoney St", "Park St"],
    "brixton": ["Coldharbour Lane", "Atlantic Rd", "Electric Ave", "Acre Lane", "Brixton Rd"],
}

# fmt: off
# Each venue: (name, type, hood, description,
#              price_band, avg_spend, rating, noise,
#              bookable, date, group, late_night, after_midnight,
#              dress_code, popularity,
#              vibes, cuisines, genres)

VENUES = [
    # ── Soho (15) ──────────────────────────────────────────────
    ("Polpetto", "restaurant", "soho", "Intimate Italian small plates above a Soho pub",
     3, 42, 4.3, 2, True, True, False, False, False, None, 0.78,
     ["intimate", "romantic"], ["Italian"], []),
    ("Koya Bar", "restaurant", "soho", "Counter-seat udon and Japanese comfort food",
     2, 22, 4.4, 2, False, False, False, False, False, None, 0.82,
     ["relaxed", "affordable"], ["Japanese"], []),
    ("Brasserie Zédel", "restaurant", "soho", "Grand Parisian brasserie hidden below Piccadilly",
     2, 30, 4.2, 3, True, True, True, False, False, None, 0.85,
     ["bougie", "group-friendly"], ["French"], []),
    ("Kiln", "restaurant", "soho", "Fiery Thai grill dishes cooked over charcoal",
     2, 28, 4.5, 3, False, False, False, False, False, None, 0.80,
     ["lively", "affordable"], ["Thai"], []),
    ("The Palomar", "restaurant", "soho", "Vibrant Middle Eastern and Mediterranean sharing plates",
     3, 48, 4.4, 3, True, True, False, False, False, None, 0.83,
     ["stylish", "date-night"], ["Middle Eastern"], []),
    ("Noble Rot Soho", "restaurant", "soho", "Wine-focused Modern European dining with rare bottles",
     4, 65, 4.5, 2, True, True, False, False, False, None, 0.75,
     ["romantic", "wine-led"], ["Modern European"], []),
    ("Bar Termini", "bar", "soho", "Tiny Italian-style cocktail bar with perfect Negronis",
     3, 38, 4.6, 2, False, True, False, False, False, None, 0.80,
     ["intimate", "stylish"], [], []),
    ("Swift Soho", "bar", "soho", "Two-floor cocktail bar — upstairs quick drinks, downstairs late lounge",
     3, 40, 4.5, 3, False, True, False, True, True, None, 0.82,
     ["date-night", "stylish"], [], []),
    ("The French House", "bar", "soho", "Legendary bohemian pub — no pints, half-measures only",
     2, 20, 4.1, 3, False, False, True, False, False, None, 0.70,
     ["relaxed", "affordable"], [], []),
    ("Cahoots", "bar", "soho", "1940s underground-station themed cocktail bar",
     3, 36, 4.2, 3, True, False, True, True, True, None, 0.76,
     ["lively", "group-friendly"], [], []),
    ("Disrepute", "bar", "soho", "Late-night basement cocktail den with rotating menus",
     4, 50, 4.3, 2, True, True, False, True, True, None, 0.72,
     ["late-night", "bougie"], [], []),
    ("The Blue Posts", "bar", "soho", "Cosy wine bar upstairs, craft cocktails downstairs",
     3, 35, 4.4, 2, False, True, False, False, False, None, 0.74,
     ["intimate", "wine-led"], [], []),
    ("Cirque le Soir", "club", "soho", "Theatrical bottle-service club with circus performers",
     5, 100, 3.8, 5, True, False, True, True, True, "Smart", 0.70,
     ["bougie", "chaotic", "late-night"], [], ["open format"]),
    ("The Box Soho", "club", "soho", "Provocative late-night cabaret and club",
     5, 90, 3.9, 5, True, False, True, True, True, "Smart", 0.75,
     ["chaotic", "late-night", "bougie"], [], ["open format"]),
    ("Freedom Bar", "club", "soho", "Long-running Soho club with DJ sets and dancing",
     2, 25, 3.7, 4, False, False, True, True, True, None, 0.65,
     ["lively", "group-friendly", "late-night"], [], ["disco", "open format"]),

    # ── Shoreditch (14) ────────────────────────────────────────
    ("Smokestak", "restaurant", "shoreditch", "Industrial-chic BBQ with serious smoked meats",
     3, 40, 4.4, 3, True, False, True, False, False, None, 0.84,
     ["lively", "group-friendly"], ["British"], []),
    ("Brat", "restaurant", "shoreditch", "Basque-inspired open-fire cooking above a pub",
     4, 62, 4.6, 3, True, True, False, False, False, None, 0.88,
     ["stylish", "date-night"], ["British"], []),
    ("Ceviche Old Street", "restaurant", "shoreditch", "Peruvian ceviche bar with pisco sours and loud music",
     3, 38, 4.2, 3, True, False, True, False, False, None, 0.72,
     ["lively", "group-friendly"], ["Mexican"], []),
    ("Gunpowder", "restaurant", "shoreditch", "Bold Indian small plates in a tiny buzzy room",
     2, 30, 4.5, 3, True, True, False, False, False, None, 0.80,
     ["intimate", "lively"], ["Middle Eastern"], []),
    ("Callooh Callay", "bar", "shoreditch", "Award-winning cocktail bar with a hidden back room",
     3, 40, 4.5, 3, True, True, False, True, True, None, 0.85,
     ["stylish", "music-forward"], [], ["disco"]),
    ("Nightjar", "bar", "shoreditch", "Speakeasy cocktails and nightly live jazz performances",
     4, 50, 4.7, 3, True, True, False, True, True, None, 0.88,
     ["intimate", "music-forward"], [], ["jazz", "live music"]),
    ("Queen of Hoxton", "bar", "shoreditch", "Rooftop bar with seasonal themes and weekend DJs",
     2, 28, 4.1, 3, False, False, True, True, True, None, 0.78,
     ["lively", "group-friendly"], [], ["open format"]),
    ("Happiness Forgets", "bar", "shoreditch", "Basement cocktail bar focused on simplicity and craft",
     3, 38, 4.6, 2, True, True, False, False, False, None, 0.82,
     ["intimate", "date-night"], [], []),
    ("Breaking Ground", "bar", "shoreditch", "Neighbourhood bar with natural wines and small plates",
     2, 24, 4.0, 2, False, False, False, False, False, None, 0.60,
     ["relaxed", "affordable"], [], []),
    ("The Hoxton Bar", "bar", "shoreditch", "Spacious hotel bar with group-friendly seating and DJs",
     3, 34, 4.0, 3, False, False, True, True, False, None, 0.72,
     ["group-friendly", "relaxed"], [], ["open format"]),
    ("XOYO", "club", "shoreditch", "Essential Shoreditch club — rotating residencies and serious sound",
     2, 25, 4.3, 5, False, False, True, True, True, None, 0.90,
     ["music-forward", "late-night", "lively"], [], ["house", "techno"]),
    ("Cargo", "club", "shoreditch", "Railway-arch club with outdoor terrace and eclectic bookings",
     2, 22, 3.9, 4, False, False, True, True, True, None, 0.75,
     ["lively", "group-friendly", "late-night"], [], ["open format", "hip hop"]),
    ("Village Underground", "club", "shoreditch", "Converted warehouse hosting live music and club nights",
     2, 20, 4.2, 5, False, False, True, True, True, None, 0.80,
     ["music-forward", "lively"], [], ["live music", "house"]),
    ("Brick Lane Tap Room", "club", "shoreditch", "Craft beer meets weekend DJ sets on Brick Lane",
     1, 18, 3.8, 4, False, False, True, True, True, None, 0.62,
     ["affordable", "group-friendly", "late-night"], [], ["hip hop", "afrobeats"]),

    # ── Camden (12) ────────────────────────────────────────────
    ("Shaka Zulu", "restaurant", "camden", "South African-themed statement restaurant by the canal",
     4, 55, 4.0, 4, True, False, True, False, False, None, 0.72,
     ["bougie", "group-friendly"], ["Steakhouse"], []),
    ("Manna", "restaurant", "camden", "Long-standing plant-based Modern European fine dining",
     3, 45, 4.3, 2, True, True, False, False, False, None, 0.65,
     ["romantic", "intimate"], ["Modern European"], []),
    ("Namaaste Kitchen", "restaurant", "camden", "Reliable North Indian cooking on Parkway",
     2, 25, 4.1, 2, True, False, True, False, False, None, 0.68,
     ["affordable", "group-friendly"], ["Middle Eastern"], []),
    ("The Cheese Bar", "restaurant", "camden", "All-cheese menu in Camden Market — fondue, toasties, boards",
     2, 22, 4.0, 3, False, False, True, False, False, None, 0.70,
     ["relaxed", "group-friendly"], ["British"], []),
    ("The Lock Tavern", "bar", "camden", "Canal-side pub with rooftop and weekend live music",
     2, 20, 4.0, 3, False, False, True, False, False, None, 0.72,
     ["relaxed", "group-friendly"], [], ["live music"]),
    ("Blues Kitchen Camden", "bar", "camden", "Live blues, bourbon, and BBQ every night of the week",
     2, 28, 4.2, 4, False, False, True, True, True, None, 0.80,
     ["lively", "music-forward"], [], ["live music", "jazz"]),
    ("The Jazz Cafe", "bar", "camden", "Iconic two-floor venue for jazz, soul, and funk",
     3, 35, 4.4, 4, True, True, False, True, True, None, 0.85,
     ["music-forward", "stylish"], [], ["jazz", "live music"]),
    ("Proud Camden", "bar", "camden", "Horse hospital turned bar with live acts and club nights",
     2, 24, 3.9, 4, False, False, True, True, True, None, 0.74,
     ["lively", "group-friendly"], [], ["live music", "open format"]),
    ("BrewDog Camden", "bar", "camden", "Craft beer bar with long tap list and casual vibes",
     2, 22, 3.8, 3, False, False, True, False, False, None, 0.60,
     ["affordable", "relaxed"], [], []),
    ("Koko", "club", "camden", "Grand Camden theatre reborn as a multi-floor music venue and club",
     3, 35, 4.3, 5, True, False, True, True, True, None, 0.90,
     ["music-forward", "late-night", "lively"], [], ["house", "disco", "live music"]),
    ("Electric Ballroom", "club", "camden", "Legendary Camden venue for indie, punk, and club nights",
     2, 20, 4.0, 5, False, False, True, True, True, None, 0.78,
     ["lively", "late-night", "chaotic"], [], ["live music", "open format"]),
    ("The Underworld", "club", "camden", "Basement club beneath the World's End pub — heavy music focus",
     2, 18, 3.9, 5, False, False, True, True, True, None, 0.70,
     ["chaotic", "music-forward", "late-night"], [], ["live music"]),

    # ── Peckham (10) ───────────────────────────────────────────
    ("Kudu", "restaurant", "peckham", "South African-influenced Modern European on Queen's Road",
     3, 45, 4.5, 2, True, True, False, False, False, None, 0.82,
     ["stylish", "date-night"], ["Modern European"], []),
    ("Levan", "restaurant", "peckham", "Natural wine-led European small plates on Blenheim Grove",
     3, 42, 4.4, 2, True, True, False, False, False, None, 0.80,
     ["wine-led", "intimate"], ["Modern European"], []),
    ("Mr Bao", "restaurant", "peckham", "Taiwanese bao buns and small plates on Rye Lane",
     1, 16, 4.3, 2, False, False, True, False, False, None, 0.75,
     ["affordable", "relaxed"], ["Korean"], []),
    ("Peckham Levels", "bar", "peckham", "Multi-storey car park turned food hall and bar with rooftop",
     1, 18, 4.0, 3, False, False, True, True, False, None, 0.82,
     ["lively", "group-friendly", "affordable"], [], []),
    ("Forza Wine", "bar", "peckham", "Tiny Italian wine bar with boards and pasta on the side",
     2, 30, 4.4, 2, False, True, False, False, False, None, 0.76,
     ["wine-led", "date-night"], [], []),
    ("The CLF Art Cafe", "bar", "peckham", "Community arts space with cheap drinks and DJ nights",
     1, 14, 3.8, 3, False, False, True, True, True, None, 0.68,
     ["affordable", "lively"], [], ["open format"]),
    ("Canopy Beer Co", "bar", "peckham", "Railway arch brewery taproom with street food trucks",
     1, 16, 4.0, 3, False, False, True, False, False, None, 0.65,
     ["relaxed", "group-friendly", "affordable"], [], []),
    ("Bar Story", "bar", "peckham", "Late-night Peckham bar under the railway arches",
     1, 15, 3.9, 3, False, False, True, True, True, None, 0.72,
     ["affordable", "lively", "late-night"], [], ["open format"]),
    ("Rye Wax", "club", "peckham", "Basement club and record shop in Peckham Levels",
     1, 15, 4.1, 5, False, False, True, True, True, None, 0.74,
     ["music-forward", "late-night", "affordable"], [], ["house", "techno"]),
    ("Copeland Social", "club", "peckham", "Industrial warehouse club space on Copeland Road",
     2, 20, 4.0, 5, False, False, True, True, True, None, 0.70,
     ["lively", "group-friendly", "late-night"], [], ["afrobeats", "hip hop"]),

    # ── Hackney (12) ───────────────────────────────────────────
    ("Bright", "restaurant", "hackney", "Michelin-star neighbourhood restaurant on Westgate Street",
     4, 65, 4.7, 2, True, True, False, False, False, None, 0.85,
     ["stylish", "date-night"], ["Modern European"], []),
    ("Pidgin", "restaurant", "hackney", "Weekly-changing four-course set menu in a tiny room",
     3, 48, 4.5, 2, True, True, False, False, False, None, 0.78,
     ["intimate", "wine-led"], ["Modern European"], []),
    ("Mangal 2", "restaurant", "hackney", "Turkish ocakbasi grill with an artist following",
     2, 25, 4.3, 3, False, False, True, False, False, None, 0.74,
     ["affordable", "relaxed"], ["Middle Eastern"], []),
    ("Yardbird", "restaurant", "hackney", "Korean fried chicken and soju in a lively setting",
     2, 28, 4.1, 3, False, False, True, False, False, None, 0.70,
     ["lively", "group-friendly"], ["Korean"], []),
    ("Original Sin", "bar", "hackney", "Natural wine bar in a former off-licence on Stoke Newington Road",
     2, 30, 4.4, 2, False, True, False, False, False, None, 0.76,
     ["wine-led", "date-night"], [], []),
    ("Coupette", "bar", "hackney", "French-inflected cocktail bar with calvados specialities",
     3, 38, 4.5, 2, True, True, False, False, False, None, 0.80,
     ["stylish", "intimate"], [], []),
    ("The Cock Tavern", "bar", "hackney", "No-frills Mare Street pub with good beer and zero pretence",
     1, 14, 3.9, 3, False, False, True, False, False, None, 0.58,
     ["relaxed", "affordable"], [], []),
    ("NT's Loft", "bar", "hackney", "Upstairs DJ bar with vinyl selectors and creative cocktails",
     2, 26, 4.1, 4, False, False, True, True, True, None, 0.68,
     ["music-forward", "lively"], [], ["house", "disco"]),
    ("Satan's Whiskers", "bar", "hackney", "Late-night cocktail bar with a no-rules energy",
     2, 28, 4.3, 3, False, False, True, True, True, None, 0.75,
     ["late-night", "chaotic", "lively"], [], []),
    ("Oslo", "club", "hackney", "Hackney Central club with world-class techno programming",
     2, 22, 4.4, 5, False, False, True, True, True, None, 0.84,
     ["music-forward", "late-night"], [], ["techno", "house"]),
    ("Oval Space", "club", "hackney", "Converted warehouse with views of the gas holders",
     3, 28, 4.3, 5, False, False, True, True, True, None, 0.82,
     ["music-forward", "late-night", "stylish"], [], ["techno", "house"]),
    ("Paper Dress Vintage", "club", "hackney", "Vintage shop by day, gig and club venue by night",
     1, 15, 4.0, 4, False, False, True, True, True, None, 0.66,
     ["lively", "affordable", "music-forward"], [], ["live music", "disco"]),

    # ── Covent Garden (12) ─────────────────────────────────────
    ("Frenchie", "restaurant", "covent-garden", "Parisian small plates and natural wines on Henrietta Street",
     3, 50, 4.4, 2, True, True, False, False, False, None, 0.82,
     ["stylish", "date-night"], ["French"], []),
    ("Spring Restaurant", "restaurant", "covent-garden", "Elegant British-Italian cooking in Somerset House",
     4, 70, 4.5, 2, True, True, False, False, False, None, 0.80,
     ["romantic", "bougie"], ["Modern European"], []),
    ("Cora Pearl", "restaurant", "covent-garden", "Kitty Fisher's sibling with wine-led Modern European food",
     4, 60, 4.3, 2, True, True, False, False, False, None, 0.76,
     ["wine-led", "date-night"], ["Modern European"], []),
    ("Flat Iron", "restaurant", "covent-garden", "Flat iron steak and nothing else — simple, affordable, good",
     1, 18, 4.2, 3, False, False, True, False, False, None, 0.85,
     ["affordable", "group-friendly"], ["Steakhouse"], []),
    ("Sushisamba CG", "restaurant", "covent-garden", "Japanese-Brazilian-Peruvian fusion in the Opera Quarter",
     5, 85, 4.1, 3, True, True, False, False, False, "Smart casual", 0.78,
     ["bougie", "stylish"], ["Japanese"], []),
    ("Experimental Cocktail Club", "bar", "covent-garden", "Hidden speakeasy with inventive cocktails and low lighting",
     3, 42, 4.5, 2, True, True, False, True, True, None, 0.84,
     ["intimate", "date-night"], [], []),
    ("The Alchemist CG", "bar", "covent-garden", "Theatrical cocktail bar with smoke, colour, and drama",
     3, 38, 4.0, 3, True, False, True, False, False, None, 0.74,
     ["stylish", "group-friendly"], [], []),
    ("Rules Bar", "bar", "covent-garden", "Bar at London's oldest restaurant — classic cocktails, old-world feel",
     4, 48, 4.2, 2, True, True, False, False, False, None, 0.68,
     ["romantic", "bougie"], [], []),
    ("Henrietta Bar", "bar", "covent-garden", "Hotel cocktail bar with floral-forward drinks and soft lighting",
     3, 40, 4.3, 2, True, True, False, False, False, None, 0.72,
     ["romantic", "stylish"], [], []),
    ("Punch Room", "bar", "covent-garden", "Intimate punch-bowl bar inside The London Edition",
     4, 52, 4.4, 2, True, True, False, False, False, None, 0.70,
     ["intimate", "bougie", "wine-led"], [], []),
    ("The Crypt", "club", "covent-garden", "Underground club beneath St Martin-in-the-Fields church",
     2, 22, 3.8, 4, False, False, True, True, True, None, 0.62,
     ["late-night", "lively"], [], ["open format", "disco"]),
    ("Roadhouse", "club", "covent-garden", "American-style live music venue with late-night dancing",
     2, 20, 3.7, 4, False, False, True, True, True, None, 0.60,
     ["group-friendly", "lively", "late-night"], [], ["live music", "open format"]),

    # ── Notting Hill (10) ──────────────────────────────────────
    ("The Ledbury", "restaurant", "notting-hill", "Two-Michelin-star Modern European destination dining",
     5, 120, 4.8, 1, True, True, False, False, False, "Smart casual", 0.92,
     ["bougie", "romantic"], ["Modern European"], []),
    ("Core by Clare Smyth", "restaurant", "notting-hill", "Three-star chef's neighbourhood fine dining",
     5, 110, 4.8, 1, True, True, False, False, False, "Smart casual", 0.90,
     ["bougie", "date-night"], ["Modern European"], []),
    ("Farmacy", "restaurant", "notting-hill", "Plant-based dining in a light and airy Westbourne Grove space",
     3, 40, 4.1, 2, True, True, False, False, False, None, 0.68,
     ["relaxed", "stylish"], ["Modern European"], []),
    ("Chakra", "restaurant", "notting-hill", "Modern Indian with tasting menus on Kensington Park Road",
     3, 45, 4.2, 2, True, True, True, False, False, None, 0.70,
     ["stylish", "group-friendly"], ["Middle Eastern"], []),
    ("Mazi", "restaurant", "notting-hill", "Contemporary Greek cooking with a romantic courtyard",
     3, 42, 4.3, 2, True, True, False, False, False, None, 0.74,
     ["romantic", "wine-led"], ["Italian"], []),
    ("The Distillery", "bar", "notting-hill", "Gin distillery and cocktail bar on Portobello Road",
     3, 36, 4.2, 2, True, True, False, False, False, None, 0.76,
     ["stylish", "date-night"], [], []),
    ("Beach Blanket Babylon", "bar", "notting-hill", "Gothic-baroque bar with ornate interiors and cocktails",
     3, 40, 4.0, 3, True, False, True, True, False, None, 0.70,
     ["bougie", "lively"], [], []),
    ("Trailer Happiness", "bar", "notting-hill", "Tiki cocktails in a kitschy basement on Portobello Road",
     2, 28, 4.1, 3, False, False, True, True, True, None, 0.72,
     ["lively", "affordable"], [], ["disco"]),
    ("The Sun in Splendour", "bar", "notting-hill", "Corner pub with a sunny beer garden and Sunday roasts",
     2, 22, 3.9, 2, False, False, True, False, False, None, 0.60,
     ["relaxed", "group-friendly"], [], []),
    ("Notting Hill Arts Club", "club", "notting-hill", "Basement club with eclectic DJ bookings and live acts",
     2, 20, 4.0, 4, False, False, True, True, True, None, 0.72,
     ["lively", "music-forward", "late-night"], [], ["open format", "live music"]),

    # ── Dalston (10) ───────────────────────────────────────────
    ("Mangal 1 Dalston", "restaurant", "dalston", "Legendary Dalston ocakbasi with charcoal-grilled kebabs",
     1, 18, 4.2, 3, False, False, True, False, False, None, 0.74,
     ["affordable", "group-friendly"], ["Middle Eastern"], []),
    ("Petit Pois", "restaurant", "dalston", "Charming French bistro on a Dalston side street",
     3, 40, 4.3, 2, True, True, False, False, False, None, 0.70,
     ["intimate", "date-night"], ["French"], []),
    ("Dalston Superstore", "bar", "dalston", "Queer bar and club with art, DJs, and all-night energy",
     2, 22, 4.2, 4, False, False, True, True, True, None, 0.82,
     ["lively", "late-night", "chaotic"], [], ["house", "disco"]),
    ("Brilliant Corners", "bar", "dalston", "Japanese-inspired bar with an audiophile-grade sound system",
     2, 28, 4.5, 3, False, True, False, True, True, None, 0.80,
     ["music-forward", "intimate"], [], ["jazz", "house"]),
    ("The Shacklewell Arms", "bar", "dalston", "DIY pub with live bands, cheap pints, and art shows",
     1, 14, 3.9, 4, False, False, True, True, True, None, 0.68,
     ["affordable", "lively", "music-forward"], [], ["live music"]),
    ("Ridley Road Bar", "bar", "dalston", "Relaxed Dalston bar with global street food and cocktails",
     1, 16, 4.0, 3, False, False, True, True, False, None, 0.64,
     ["relaxed", "affordable"], [], []),
    ("Three Sheets", "bar", "dalston", "Understated cocktail bar with a stripped-back menu",
     3, 36, 4.4, 2, True, True, False, False, False, None, 0.78,
     ["stylish", "date-night"], [], []),
    ("EGG London", "club", "dalston", "Multi-room techno institution with garden and terrace",
     2, 25, 4.2, 5, False, False, True, True, True, None, 0.86,
     ["music-forward", "late-night"], [], ["techno", "house"]),
    ("The Alibi", "club", "dalston", "No-frills late-night basement club on Kingsland High Street",
     1, 15, 3.8, 5, False, False, True, True, True, None, 0.64,
     ["affordable", "late-night", "lively"], [], ["hip hop", "open format"]),
    ("Birthdays", "club", "dalston", "Two-floor Dalston venue with live music and DJ sets",
     2, 18, 4.0, 4, False, False, True, True, True, None, 0.70,
     ["lively", "music-forward"], [], ["live music", "disco"]),

    # ── London Bridge (13) ─────────────────────────────────────
    ("José", "restaurant", "london-bridge", "Standing-room tapas bar on Bermondsey Street",
     2, 28, 4.4, 3, False, True, False, False, False, None, 0.80,
     ["intimate", "wine-led"], ["Italian"], []),
    ("Padella", "restaurant", "london-bridge", "Hand-rolled pasta at Borough Market — always a queue",
     2, 22, 4.6, 3, False, False, True, False, False, None, 0.92,
     ["affordable", "lively"], ["Italian"], []),
    ("Arabica Bar and Kitchen", "restaurant", "london-bridge", "Levantine sharing plates under Borough Market arches",
     2, 30, 4.2, 3, True, False, True, False, False, None, 0.74,
     ["lively", "group-friendly"], ["Middle Eastern"], []),
    ("Oxo Tower Brasserie", "restaurant", "london-bridge", "Thames-view brasserie with a Modern European menu",
     4, 70, 4.1, 2, True, True, False, False, False, "Smart casual", 0.76,
     ["romantic", "bougie"], ["Modern European"], []),
    ("Hawksmoor Borough", "restaurant", "london-bridge", "Premium British steakhouse in a former hop warehouse",
     4, 75, 4.5, 3, True, True, False, False, False, None, 0.88,
     ["date-night", "bougie"], ["Steakhouse"], []),
    ("Nine Lives", "bar", "london-bridge", "Late-night cocktail bar with DJs and a party atmosphere",
     2, 28, 4.2, 4, False, False, True, True, True, None, 0.76,
     ["late-night", "lively"], [], ["house", "disco"]),
    ("The Woolpack", "bar", "london-bridge", "Traditional Bermondsey pub with craft ales and a garden",
     2, 20, 3.9, 2, False, False, True, False, False, None, 0.56,
     ["relaxed", "affordable"], [], []),
    ("Bermondsey Arts Club", "bar", "london-bridge", "Stylish cocktail bar in a converted public toilet",
     3, 40, 4.3, 2, True, True, False, True, False, None, 0.74,
     ["stylish", "intimate"], [], []),
    ("Tanner and Co", "bar", "london-bridge", "Large warehouse bar ideal for group drinks and events",
     2, 26, 3.9, 3, True, False, True, False, False, None, 0.66,
     ["group-friendly", "relaxed"], [], []),
    ("Boro Bistro", "bar", "london-bridge", "French-inspired wine bar under the railway by Borough Market",
     2, 28, 4.1, 2, False, True, False, False, False, None, 0.70,
     ["wine-led", "date-night"], [], []),
    ("Corsica Studios", "club", "london-bridge", "Two-room club with world-class techno and experimental bookings",
     2, 22, 4.5, 5, False, False, True, True, True, None, 0.88,
     ["music-forward", "late-night"], [], ["techno", "house"]),
    ("Ministry of Sound", "club", "london-bridge", "Legendary superclub with a Funktion-One system and global DJs",
     3, 35, 4.2, 5, True, False, True, True, True, "No sportswear", 0.92,
     ["music-forward", "late-night", "bougie"], [], ["house", "techno"]),
    ("The Vault", "club", "london-bridge", "Underground arches club with a mix of hip hop and house",
     2, 20, 3.8, 4, False, False, True, True, True, None, 0.64,
     ["lively", "group-friendly", "late-night"], [], ["hip hop", "open format"]),

    # ── Brixton (12) ───────────────────────────────────────────
    ("Franco Manca", "restaurant", "brixton", "Sourdough pizza by the slice in Brixton Market",
     1, 14, 4.3, 3, False, False, True, False, False, None, 0.84,
     ["affordable", "relaxed"], ["Italian"], []),
    ("Nanban", "restaurant", "brixton", "Japanese ramen and izakaya dishes in Brixton Village",
     2, 24, 4.2, 3, False, False, True, False, False, None, 0.74,
     ["lively", "affordable"], ["Japanese"], []),
    ("Salon Brixton", "restaurant", "brixton", "Upstairs dining room serving seasonal British small plates",
     3, 45, 4.4, 2, True, True, False, False, False, None, 0.72,
     ["stylish", "date-night"], ["Modern European"], []),
    ("Pop Brixton", "bar", "brixton", "Shipping container village with bars, food stalls, and DJs",
     1, 16, 3.9, 3, False, False, True, True, False, None, 0.78,
     ["lively", "group-friendly", "affordable"], [], ["open format"]),
    ("Hootananny", "bar", "brixton", "Live music and reggae bar with a big dancefloor",
     1, 16, 4.1, 4, False, False, True, True, True, None, 0.76,
     ["lively", "music-forward"], [], ["live music", "afrobeats"]),
    ("The Prince of Wales", "bar", "brixton", "Rooftop terrace pub on Coldharbour Lane",
     2, 22, 4.0, 3, False, False, True, False, False, None, 0.68,
     ["relaxed", "group-friendly"], [], []),
    ("Craft Beer Co Brixton", "bar", "brixton", "Craft beer bar with 30+ taps and a laid-back crowd",
     2, 22, 4.0, 3, False, False, True, False, False, None, 0.62,
     ["affordable", "relaxed"], [], []),
    ("Lost in Brixton", "bar", "brixton", "Rooftop cocktails and DJ sets above Brixton Village",
     2, 26, 4.0, 3, False, False, True, True, True, None, 0.72,
     ["lively", "group-friendly"], [], ["open format", "afrobeats"]),
    ("Phonox", "club", "brixton", "Premier Brixton club with house, disco, and world-class DJs",
     2, 25, 4.4, 5, False, False, True, True, True, None, 0.88,
     ["music-forward", "late-night"], [], ["house", "disco"]),
    ("Electric Brixton", "club", "brixton", "Former cinema turned live music and club venue",
     2, 22, 4.1, 5, False, False, True, True, True, None, 0.82,
     ["lively", "late-night", "music-forward"], [], ["live music", "afrobeats"]),
    ("Prince of Peckham Brixton", "club", "brixton", "Rooftop club with afrobeats, dancehall, and city views",
     2, 20, 4.0, 5, False, False, True, True, True, None, 0.70,
     ["lively", "group-friendly", "late-night"], [], ["afrobeats", "hip hop"]),
    ("Club 414", "club", "brixton", "Long-running underground techno club on Coldharbour Lane",
     1, 15, 4.0, 5, False, False, True, True, True, None, 0.72,
     ["music-forward", "late-night", "affordable"], [], ["techno", "house"]),
]

# Events spread across March–April 2026
EVENTS = [
    ("XOYO", "Pulse: Ben UFO All Night", "2026-03-14T22:00", "2026-03-15T05:00", "house", 18),
    ("XOYO", "Midland Presents", "2026-03-21T22:00", "2026-03-22T05:00", "techno", 20),
    ("Corsica Studios", "Hessle Audio Showcase", "2026-03-14T23:00", "2026-03-15T06:00", "techno", 15),
    ("Corsica Studios", "Rhythm Section Night", "2026-03-28T23:00", "2026-03-29T06:00", "house", 15),
    ("Ministry of Sound", "Defected Records: Spring Sessions", "2026-03-15T23:00", "2026-03-16T06:00", "house", 25),
    ("Ministry of Sound", "Renaissance: Ibiza Preview", "2026-04-05T23:00", "2026-04-06T06:00", "house", 30),
    ("Phonox", "Horse Meat Disco: Brixton", "2026-03-14T22:00", "2026-03-15T04:00", "disco", 12),
    ("Phonox", "Anz All Night", "2026-03-28T22:00", "2026-03-29T04:00", "house", 15),
    ("EGG London", "Concrete: 12-Hour Rave", "2026-03-15T14:00", "2026-03-16T02:00", "techno", 20),
    ("EGG London", "Fuse London Takeover", "2026-04-04T23:00", "2026-04-05T08:00", "techno", 22),
    ("Oslo", "Dekmantel Soundsystem", "2026-03-21T23:00", "2026-03-22T05:00", "techno", 18),
    ("Oslo", "Peach Presents: Spring Fling", "2026-04-11T23:00", "2026-04-12T05:00", "house", 16),
    ("Oval Space", "Boiler Room London", "2026-03-22T20:00", "2026-03-23T03:00", "house", 22),
    ("Koko", "Sink The Pink: Neon Ball", "2026-03-20T21:00", "2026-03-21T03:00", "disco", 20),
    ("Koko", "Late Night Tales Live", "2026-04-03T20:00", "2026-04-04T02:00", "live music", 25),
    ("Electric Ballroom", "Camden Rocks Mini-Festival", "2026-03-22T19:00", "2026-03-23T02:00", "live music", 15),
    ("Electric Brixton", "Bonobo DJ Set", "2026-03-29T21:00", "2026-03-30T03:00", "house", 28),
    ("Electric Brixton", "Channel One Sound System", "2026-04-12T21:00", "2026-04-13T03:00", "afrobeats", 15),
    ("Village Underground", "Jazz Re:freshed Spring Sessions", "2026-03-19T20:00", "2026-03-20T00:00", "jazz", 18),
    ("The Jazz Cafe", "Kamasi Washington Trio", "2026-03-27T20:00", "2026-03-28T00:00", "jazz", 30),
    ("The Jazz Cafe", "Ezra Collective Late Show", "2026-04-10T21:00", "2026-04-11T01:00", "jazz", 25),
    ("Nightjar", "Django Reinhardt Tribute Night", "2026-03-16T20:00", "2026-03-17T00:00", "jazz", 15),
    ("Blues Kitchen Camden", "Blues Brunch Sessions", "2026-03-15T13:00", "2026-03-15T17:00", "live music", 10),
    ("Callooh Callay", "Spring Cocktail Menu Launch Party", "2026-03-13T19:00", "2026-03-14T01:00", "disco", 0),
    ("Dalston Superstore", "Chapter 10: Queer Rave", "2026-03-21T23:00", "2026-03-22T05:00", "house", 10),
    ("Notting Hill Arts Club", "Hip Hop Karaoke", "2026-03-20T20:00", "2026-03-21T01:00", "hip hop", 8),
    ("Hootananny", "Reggae Roast: Spring Edition", "2026-03-15T20:00", "2026-03-16T02:00", "afrobeats", 8),
    ("Copeland Social", "Peckham All-Dayer", "2026-04-05T14:00", "2026-04-06T00:00", "afrobeats", 12),
    ("Paper Dress Vintage", "Hackney Indie Showcase", "2026-03-18T20:00", "2026-03-19T00:00", "live music", 7),
    ("Brick Lane Tap Room", "Afrobeats vs Amapiano", "2026-03-22T22:00", "2026-03-23T04:00", "afrobeats", 10),
]
# fmt: on
